[package]
name = "terminal-web-client"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
